language: java
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
matrix:
  allow_failures:
    - jdk: oraclejdk8
  fast_finish: true
script: mvn test -Dsurefire.useFile=false
