language: java
dist: trusty
sudo: false
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
matrix:
  fast_finish: true
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/endpoint/c6cc872b193cbad86273/529f9078ed5ab0b3bf04ef9a/
script: mvn test -Dsurefire.useFile=false
after_success:
  - mvn clean cobertura:cobertura coveralls:report -Dmaven.plugin.skip=true -B
